### ISSUE TITLE
Feature request: add GMP API compatibility, gmpbench results

### ISSUE THREAD

**Issue by oscarbg** [NVlabs/xmp#1]
Hi,
Just seen project on github but no source code still..
Would be nice if similar to how cublas, cufft provide standard API with popular CPU libraries like FFTW this cuda multiprecision library has API like GMP so codes using GMP doesn't need to be ported.. Assuming no performance is lost using this API..

**Comment by dumerrill** [comment]
Thanks for the suggestion Oscar!

Cheers,

Duane

**Comment by oscarbg** [comment]
Thanks..
I know isn't place to ask but is this library (possibly in alpha form) coming soon?

**Comment by luitjens** [comment]
Yes by mid September we should have a release.

**Comment by luitjens** [comment]
You should now be able to use this library.  The API is similar to GMP but varies slightly.  The main difference is that the API is batched.  Please see the API documentation for more details.
