### ISSUE TITLE
Error in doc

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [NVlabs/xmp#3]
there is copy-paste error in example in https://github.com/NVlabs/xmp/blob/master/docs/xmp.docx

  XMP_CHECK_ERROR(xmpIntegersImport(handle,base,N,limbs,-1,sizeof(uint32_t),0,0,b));
  XMP_CHECK_ERROR(xmpIntegersImport(handle,exp,1,limbs,-1,sizeof(uint32_t),0,0,b));
  XMP_CHECK_ERROR(xmpIntegersImport(handle,mod,1,limbs,-1,sizeof(uint32_t),0,0,b));

last parameter here should be b/e/m rather than b/b/b

**Comment by luitjens** [comment]
Thank you,

Fixed
